version: '3.9'

services:
  mysql:
    image: mysql:8.0.33
    container_name: auth-mysql-server
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#      MYSQL_DATABASE: ''
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
    networks:
      - auth-mysql-network

networks:
  auth-mysql-network:
    name: auth-mysql-network
    driver: bridge
